# Generated by Django 3.2.18 on 2023-03-23 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('price', models.TextField(blank=True, max_length=50)),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Fair'), (4, '4 - Good'), (5, '5 - Excellent')])),
                ('content', models.TextField(blank=True)),
                ('location', models.TextField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, default='../default_post_rgq6aq', upload_to='images/')),
                ('location_filter', models.CharField(choices=[('temple_bar', 'Temple Bar'), ('sandymount', 'Sandymount'), ('rathmines', 'Rathmines'), ('portobello', 'Portobello'), ('ballsbridge', 'Ballsbridge'), ('dublin_docklands', 'Dublin Docklands'), ('smithfield', 'Smithfield'), ('cabra', 'Cabra'), ('ashtown', 'Ashtown'), ('phibsborough', 'Phibsborough')], default='none', max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
