# Generated by Django 3.2.18 on 2023-03-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
